### ISSUE TITLE
SQL Following

### ISSUE THREAD

**Issue by DUREAULT** [Chartes-TNAH/Boatlas#16]
Tu as un problème sur cette ligne-là : https://github.com/ajaniak/Boatlas/blob/fe1b0af8b108778939de6c538468697f47a4ff4f/datamodel-following.sql#L4
Tu dois déclarer ta Primary_key après la définition des champs de ta table (d'après ce que je fais pour mon modèle relation) + des index :
DROP TABLE IF EXISTS `gazetteer`.`following` ;

CREATE TABLE IF NOT EXISTS `gazetteer`.`following` (
  `f_connection_id` INT NOT NULL AUTO_INCREMENT,
  `f_place_from` INT NOT NULL,
  `f_place_to` INT NOT NULL,
  PRIMARY KEY (`relation_id`),
  INDEX `fk_following_1_idx` (`f_place_from` ASC),
  INDEX `fk_following_2_idx` (`f_place_to` ASC),
  CONSTRAINT `fk_following_1_idx`
    FOREIGN KEY (`f_place_from`)
    REFERENCES `gazetteer`.`place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_following_2_idx`
    FOREIGN KEY (`f_place_to`)
    REFERENCES `gazetteer`.`place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

**Comment by ajaniak** [comment]
c'est pas le bon fichier Ella

**Comment by ajaniak** [comment]
`DROP TABLE IF EXISTS `gazetteer`.`link_type` ;

CREATE TABLE IF NOT EXISTS `gazetteer`.`link_type` (
  `link_type_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `link_type_name`  VARCHAR(45) NOT NULL,
  `link_type_description`VARCHAR(240) NOT NULL,
  PRIMARY KEY (`link_type_id`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `gazetteer`.`link` ;

CREATE TABLE IF NOT EXISTS `gazetteer`.`link` (
  `link_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `link_place1_id` SMALLINT NOT NULL,
  `link_place2_id` SMALLINT NOT NULL,
  `link_relation_type_id` SMALLINT NOT NULL,

  PRIMARY KEY (`link_id`),
  CONSTRAINT `fk_link_1`
    FOREIGN KEY (`link_place1_id`)
    REFERENCES `gazetteer`.`place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_link_2`
    FOREIGN KEY (`link_place2_id`)
    REFERENCES `gazetteer`.`place` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_link_3`
    FOREIGN KEY (`link_relation_type_id`)
    REFERENCES `gazetteer`.`link_type` (`link_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;`

**Comment by ajaniak** [comment]
j'avais des index mais je les ai supprimé en cherchant la cause de l'erreur

**Comment by DUREAULT** [comment]
D'accord. Je ne sais pas sur ton repository, il y avait ce fichier -là mais j'ai dû me tromper!

**Comment by ajaniak** [comment]
bizarre pourtant il était à jour quand j'ai vérifié

**Comment by DUREAULT** [comment]
Ah tu en as deux : un au même niveau que gazetteer, l'autre dans gazetteer!

**Comment by DUREAULT** [comment]
Et avec les index?

**Comment by ajaniak** [comment]
non, ERROR 1215 (HY000) at line 12: Cannot add foreign key constraint est toujours la avec ou sans l'index.

**Comment by ajaniak** [comment]
Ah c'est mon fichier initial, après je l'ai déplacé dans ton dossier

**Comment by ajaniak** [comment]
J'ai résolu le problème en revenant à un modèle avec un typage dans la table Link.
