### ISSUE TITLE
Ajout des exercices

### ISSUE THREAD

**Issue by ajaniak** [Chartes-TNAH/Boatlas#3]
@DUREAULT, 

En lisant les fichiers ce matin, j'ai l'impression que les fonctions du Gazetteer créées dans le cadre des exercices sont absents des fichiers présents sur Github. Est-ce que tu me le confirmes?

**Comment by DUREAULT** [comment]
Oui, je suis en train de les ajouter sur mon propre fork pour les merger avec notre repository commun. 
On les ajoute ensemble si tu veux ensuite ?

**Comment by ajaniak** [comment]
Non si tu les as ajoutés, je ferais un fetch upstream après ta pull request

**Comment by ajaniak** [comment]
Merci
